@ECHO off
cd /d %~dp0
mkdir Minetest
mkdir Minetest\blocks
mkdir Minetest\items
mkdir Minetest\other
cd /d %~dp0
copy "mobs\char.png" "minetest\other"
cd /d %~dp0
set targetblock="minetest\blocks"
copy "textures\blocks\bookshelf.png" "%targetblock%"
copy "textures\blocks\brick.png" "%targetblock%"
copy "textures\blocks\cactus_side.png" "%targetblock%"
copy "textures\blocks\cactus_top.png" "%targetblock%"
copy "textures\blocks\clay.png" "%targetblock%"
copy "textures\blocks\cloth_*.png" "%targetblock%"
copy "textures\blocks\dirt.png" "%targetblock%"
copy "textures\blocks\door*.png" "%targetblock%"
copy "textures\blocks\furnace*.png" "%targetblock%"
copy "textures\blocks\glass.png" "%targetblock%"
copy "textures\blocks\grass_top.png" "%targetblock%"
copy "textures\blocks\grass_side_overlay.png" "%targetblock%"
copy "textures\blocks\gravel.png" "%targetblock%"
copy "textures\blocks\ladder.png" "%targetblock%"
copy "textures\blocks\leaves_jungle.png" "%targetblock%"
copy "textures\blocks\leaves.png" "%targetblock%"
copy "textures\blocks\obsidian.png" "%targetblock%"
copy "textures\blocks\oreCoal.png" "%targetblock%"
copy "textures\blocks\rail*.png" "%targetblock%"
copy "textures\blocks\reeds.png" "%targetblock%"
copy "textures\blocks\sand.png" "%targetblock%"
copy "textures\blocks\sandstone_top.png" "%targetblock%"
copy "textures\blocks\sapling.png" "%targetblock%"
copy "textures\blocks\sapling_jungle.png" "%targetblock%"
copy "textures\blocks\stone.png" "%targetblock%"
copy "textures\blocks\stonebrick.png" "%targetblock%"
copy "textures\blocks\stonebricksmooth.png" "%targetblock%"
copy "textures\blocks\stoneMoss.png" "%targetblock%"
copy "textures\blocks\tallgrass.png" "%targetblock%"
copy "textures\blocks\crops_0.png" "%targetblock%"
copy "textures\blocks\crops_1.png" "%targetblock%"
copy "textures\blocks\crops_2.png" "%targetblock%"
copy "textures\blocks\crops_3.png" "%targetblock%"
copy "textures\blocks\crops_4.png" "%targetblock%"
copy "textures\blocks\tnt*.png" "%targetblock%"
copy "textures\blocks\tree_jungle.png" "%targetblock%"
copy "textures\blocks\tree_side.png" "%targetblock%"
copy "textures\blocks\tree_top.png" "%targetblock%"
copy "textures\blocks\wood_jungle.png" "%targetblock%"
copy "textures\blocks\wood.png" "%targetblock%"
copy "textures\blocks\fire_0.png" "%targetblock%"
copy "textures\blocks\lava*.png" "%targetblock%"
copy "textures\blocks\torch.png" "%targetblock%"
copy "textures\blocks\water*.png" "%targetblock%"
copy "textures\blocks\*Gold.png" "%targetblock%"
copy "textures\blocks\*Iron.png" "%targetblock%"
copy "textures\blocks\*Diamond.png" "%targetblock%"
copy "textures\blocks\deadbush.png" "%targetblock%"
set targetitem="minetest\items"
copy "textures\items\apple.png" "%targetitem%"
copy "textures\items\book.png" "%targetitem%"
copy "textures\items\brick.png" "%targetitem%"
copy "textures\items\bucket*.png" "%targetitem%"
copy "textures\items\clay.png" "%targetitem%"
copy "textures\items\coal.png" "%targetitem%"
copy "textures\items\door*.png" "%targetitem%"
copy "textures\items\dye*.png" "%targetitem%"
copy "textures\items\glassBottle.png" "%targetitem%"
copy "textures\items\hatchet*.png" "%targetitem%"
copy "textures\items\pickaxe*.png" "%targetitem%"
copy "textures\items\shovel*.png" "%targetitem%"
copy "textures\items\sword*.png" "%targetitem%"
copy "textures\items\ingotIron.png" "%targetitem%"
copy "textures\items\string.png" "%targetitem%"
copy "textures\items\ingotGold.png" "%targetitem%"
copy "textures\items\goldNugget.png" "%targetitem%"
copy "textures\items\stick.png" "%targetitem%"
cd /d %~dp0
cd Minetest\other
ren char.png "character.png"
cd /d %~dp0
cd Minetest\blocks
ren blockIron.png "default_steel_block.png"
ren bookshelf.png "default_bookshelf.png"
ren brick.png "default_brick.png"
ren cactus_top.png "default_cactus_top.png"
ren cactus_side.png "default_cactus_side.png"
ren clay.png "default_clay.png"
ren cloth_0.png "wool_white.png"
ren cloth_1.png "wool_orange.png"
ren cloth_2.png "wool_magenta.png"
ren cloth_4.png "wool_yellow.png"
ren cloth_5.png "wool_green.png"
ren cloth_6.png "wool_pink.png"
ren cloth_7.png "wool_dark_grey.png"
ren cloth_8.png "wool_grey.png"
ren cloth_9.png "wool_cyan.png"
ren cloth_10.png "wool_purple.png"
ren cloth_11.png "wool_blue.png"
ren cloth_12.png "wool_brown.png"
ren cloth_13.png "wool_dark_green.png"
ren cloth_14.png "wool_red.png"
ren cloth_15.png "wool_black.png"
ren crops_0.png "default_grass_1.png"
ren crops_1.png "default_grass_2.png"
ren crops_2.png "default_grass_3.png"
ren crops_3.png "default_grass_4.png"
ren crops_4.png "default_grass_5.png"
ren dirt.png "default_dirt.png"
ren doorIron_lower.png "door_steel_b.png"
ren doorIron_upper.png "door_steel_a.png"
ren doorWood_lower.png "door_wood_b.png"
ren doorWood_upper.png "door_wood_a.png"
ren fire_0.png "fire_basic_flame_animated.png"
ren furnace_front.png "default_furnace_front.png"
ren furnace_side.png "default_furnace_side.png"
ren furnace_top.png "default_furnace_top.png"
ren furnace_front_lit.png "default_furnace_front_active.png"
ren glass.png "default_glass.png"
ren grass_side_overlay.png "default_grass_side.png"
ren grass_top.png "default_grass.png"
ren gravel.png "default_gravel.png"
ren ladder.png "default_ladder.png"
ren lava.png "default_lava_source_animated.png"
ren lava_flow.png "default_lava_flowing_animated.png"
ren water.png "default_water_source_animated.png"
ren water_flow.png "default_water_flowing_animated.png"
ren leaves.png "default_leaves.png"
ren leaves_jungle.png "default_jungleleaves.png"
ren obsidian.png "default_obsidian.png"
ren oreCoal.png "default_mineral_coal.png"
ren rail.png "default_rail.png"
ren rail_turn.png "default_rail_curved.png"
ren reeds.png "default_papyrus.png"
ren sandstone_top.png "default_sandstone.png"
ren sand.png "default_sand.png"
ren sapling.png "default_sapling.png"
ren sapling_jungle.png "default_junglesapling.png"
ren stone.png "default_stone.png"
ren stonebrick.png "default_cobble.png"
ren stonebricksmooth.png "default_stone_brick.png"
ren stonemoss.png "default_mossycobble.png"
ren tallgrass.png "default_junglegrass.png"
ren tnt_bottom.png "default_tnt_bottom.png"
ren tnt_side.png "default_tnt_side.png"
ren tnt_top.png "default_tnt_top.png"
ren tree_jungle.png "default_jungletree.png"
ren tree_side.png "default_tree.png"
ren tree_top.png "default_tree_top.png"
ren torch.png "default_torch_on_floor_animated.png"
ren wood.png "default_wood.png"
ren wood_jungle.png "default_junglewood.png"
ren oreGold.png "default_mineral_gold.png"
ren oreIron.png "default_mineral_iron.png"
ren blockGold.png "default_gold_block.png
ren deadbush.png "default_dry_shrub.png"
ren blockDiamond.png "default_diamond_block.png"
ren oreDiamond.png "default_mineral_diamond.png"
cd /d %~dp0
cd Minetest\items
ren apple.png "default_apple.png"
ren book.png "default_book.png"
ren brick.png "default_clay_brick.png"
ren bucket.png "bucket.png"
ren bucketLava.png "bucket_lava.png"
ren bucketWater.png "bucket_water.png"
ren clay.png "default_clay_lump.png"
ren coal.png "default_coal_lump.png"
ren doorIron.png "door_steel.png"
ren doorWood.png "door_wood.png"
ren ingotIron.png "default_steel_ingot.png"
ren string.png "default_string.png"
ren glassBottle.png "vessels_glass_bottle.png"
ren hatchetDiamond.png "default_tool_diamondaxe.png"
ren hatchetGold.png "default_tool_meseaxe.png"
ren hatchetIron.png "default_tool_steelaxe.png"
ren hatchetStone.png "default_tool_stoneaxe.png"
ren hatchetWood.png "default_tool_woodaxe.png"
ren pickaxeDiamond.png "default_tool_diamondpick.png"
ren pickaxeGold.png "default_tool_mesepick.png"
ren pickaxeIron.png "default_tool_steelpick.png"
ren pickaxeStone.png "default_tool_stonepick.png"
ren pickaxeWood.png "default_tool_woodpick.png"
ren shovelDiamond.png "default_tool_diamondshovel.png"
ren shovelGold.png "default_tool_meseshovel.png"
ren shovelIron.png "default_tool_steelshovel.png"
ren shovelStone.png "default_tool_stoneshovel.png"
ren shovelWood.png "default_tool_woodshovel.png"
ren swordDiamond.png "default_tool_diamondsword.png"
ren swordGold.png "default_tool_mesesword.png"
ren swordIron.png "default_tool_steelsword.png"
ren swordStone.png "default_tool_stonesword.png"
ren swordWood.png "default_tool_woodsword.png"
ren ingotGold.png "default_gold_ingot.png"
ren goldNugget.png "default_gold_lump.png"
ren dyePowder_black.png "dye_black.png"
ren dyePowder_blua.png "dye_blua.png"
ren dyePowder_brown.png "dye_brown.png"
ren dyePowder_cyan.png "dye_cyan.png"
ren dyePowder_silver.png "dye_grey.png"
ren dyePowder_grey.png "dye_dark_grey.png"
ren dyePowder_green.png "dye_dark_green.png"
ren dyePowder_lime.png "dye_green.png"
ren dyePowder_magenta.png "dye_magenta.png"
ren dyePowder_orange.png "dye_orange.png"
ren dyePowder_pink.png "dye_pink.png"
ren dyePowder_purple.png "dye_violet.png"
ren dyePowder_red.png "dye_red.png"
ren dyePowder_white.png "dye_white.png"
ren dyePowder_yellow.png "dye_yellow.png"
ren stick.png "default_stick.png"
cd /d %~dp0
copy "textures\blocks\furnace_top.png" "minetest\blocks"
copy "textures\blocks\tree_top.png" "minetest\blocks"
copy "textures\items\glassBottle.png" "Minetest\items"
ren Minetest\blocks\furnace_top.png "default_furnace_bottom.png"
ren Minetest\blocks\tree_top.png "default_jungletree_top.png"
ren Minetest\items\glassBottle.png "vessels_glass_bottle_inv.png"
cd /d %~dp0
MOVE/Y "%~dp0Minetest\blocks\*.png" "%~dp0Minetest"
cd /d %~dp0
MOVE/Y "%~dp0Minetest\items\*.png" "%~dp0Minetest"
cd /d %~dp0
MOVE/Y "%~dp0Minetest\other\*.png" "%~dp0Minetest"
cd /d %~dp0
cd Minetest
del waterlily.png
del cloth_3.png
del fenceIron.png
cd /d %~dp0
rd/s/q armor
rd/s/q art
rd/s/q  biomesop
rd/s/q ctm
rd/s/q environment
rd/s/q fancypack
rd/s/q gui
rd/s/q item
rd/s/q title
rd/s/q misc
rd/s/q mob
rd/s/q terrain
rd/s/q textures
rd/s/q achievement
rd/s/q anim
rd/s/q font
del *.txt
del *.png
del *.properties
cd /d %~dp0
MOVE/Y "%~dp0Minetest\*.png" "%~dp0"
cd /d %~dp0
rd/s/q Minetest
del Tpconvert.bat
